version: '3.8'

services:
  maroc-bill-sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maroc-bill-sim
    ports:
      - "5000:5000"
    restart: unless-stopped
    # If you need environment variables:
    # environment:
    #   - NODE_ENV=production
    # If you need to mount volumes:
    # volumes:
    #   - ./config:/app/config 